
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Guide
{
public sealed partial class GuideConfig : Luban.BeanBase
{
    public GuideConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        GroupId = _buf.ReadInt();
        StepOrder = _buf.ReadInt();
        ForceType = _buf.ReadInt();
        ResID = _buf.ReadInt();
        TargetPath = _buf.ReadString();
        HighlightType = _buf.ReadInt();
        OffsetX = _buf.ReadFloat();
        OffsetY = _buf.ReadFloat();
        ArrowDirection = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);TriggerCondition = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); TriggerCondition.Add(_e0);}}
        AutoNext = _buf.ReadBool();
        WaitTime = _buf.ReadFloat();
//bindLanguageKeyFunc_impl
    }
	
//bindLanguageKeyField_impl

    public static GuideConfig DeserializeGuideConfig(ByteBuf _buf)
    {
        return new Guide.GuideConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 分组
    /// </summary>
    public readonly int GroupId;
    /// <summary>
    /// 组内顺序
    /// </summary>
    public readonly int StepOrder;
    /// <summary>
    /// 引导类型(0/1)
    /// </summary>
    public readonly int ForceType;
    /// <summary>
    /// GuideResConfig表内ID
    /// </summary>
    public readonly int ResID;
    /// <summary>
    /// 目标UI路径
    /// </summary>
    public readonly string TargetPath;
    /// <summary>
    /// 高亮类型
    /// </summary>
    public readonly int HighlightType;
    /// <summary>
    /// X偏移
    /// </summary>
    public readonly float OffsetX;
    /// <summary>
    /// Y偏移
    /// </summary>
    public readonly float OffsetY;
    /// <summary>
    /// 箭头方向
    /// </summary>
    public readonly int ArrowDirection;
    /// <summary>
    ///  触发条件
    /// </summary>
    public readonly System.Collections.Generic.List<string> TriggerCondition;
    /// <summary>
    /// 自动下一步
    /// </summary>
    public readonly bool AutoNext;
    /// <summary>
    /// 等待秒数
    /// </summary>
    public readonly float WaitTime;
   
    public const int __ID__ = -1266369236;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "GroupId:" + GroupId + ","
        + "StepOrder:" + StepOrder + ","
        + "ForceType:" + ForceType + ","
        + "ResID:" + ResID + ","
        + "TargetPath:" + TargetPath + ","
        + "HighlightType:" + HighlightType + ","
        + "OffsetX:" + OffsetX + ","
        + "OffsetY:" + OffsetY + ","
        + "ArrowDirection:" + ArrowDirection + ","
        + "TriggerCondition:" + Luban.StringUtil.CollectionToString(TriggerCondition) + ","
        + "AutoNext:" + AutoNext + ","
        + "WaitTime:" + WaitTime + ","
        + "}";
    }
}

}

