
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Guide
{
public sealed partial class GuideResConfig : Luban.BeanBase
{
    public GuideResConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        GuideType = _buf.ReadInt();
        ArrowIcon = _buf.ReadString();
        TipText = _buf.ReadString();
        BackgroundBG = _buf.ReadString();
        CharacterName = _buf.ReadString();
        CharacterAvatarPath = _buf.ReadString();
        CharacterPosition = _buf.ReadInt();
//bindLanguageKeyFunc_impl
    }
	
//bindLanguageKeyField_impl

    public static GuideResConfig DeserializeGuideResConfig(ByteBuf _buf)
    {
        return new Guide.GuideResConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 引导类型
    /// </summary>
    public readonly int GuideType;
    /// <summary>
    /// 引导图标
    /// </summary>
    public readonly string ArrowIcon;
    /// <summary>
    /// 提示文本
    /// </summary>
    public readonly string TipText;
    /// <summary>
    /// 背景图
    /// </summary>
    public readonly string BackgroundBG;
    /// <summary>
    /// 角色名字(对话引导才使用）
    /// </summary>
    public readonly string CharacterName;
    /// <summary>
    /// 角色立绘
    /// </summary>
    public readonly string CharacterAvatarPath;
    /// <summary>
    /// 角色立绘位置
    /// </summary>
    public readonly int CharacterPosition;
   
    public const int __ID__ = -1857047080;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "GuideType:" + GuideType + ","
        + "ArrowIcon:" + ArrowIcon + ","
        + "TipText:" + TipText + ","
        + "BackgroundBG:" + BackgroundBG + ","
        + "CharacterName:" + CharacterName + ","
        + "CharacterAvatarPath:" + CharacterAvatarPath + ","
        + "CharacterPosition:" + CharacterPosition + ","
        + "}";
    }
}

}

