
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Guide
{
public partial class TbGuideConfig:IVOFun
{
	
    private readonly System.Collections.Generic.Dictionary<int, Guide.GuideConfig> _dataMap;
    private readonly System.Collections.Generic.List<Guide.GuideConfig> _dataList;
    
    public TbGuideConfig()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Guide.GuideConfig>();
        _dataList = new System.Collections.Generic.List<Guide.GuideConfig>();
        
    }

    public System.Collections.Generic.Dictionary<int, Guide.GuideConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Guide.GuideConfig> DataList => _dataList;

    public Guide.GuideConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Guide.GuideConfig Get(int key) => _dataMap[key];
    public Guide.GuideConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

	
	public void _LoadData(ByteBuf _buf)
	{
		 for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Guide.GuideConfig _v;
	        _v = Guide.GuideConfig.DeserializeGuideConfig(_buf);
			_dataList.Add(_v);
			_dataMap.Add(_v.Id, _v);
        }
	}
	
	public void _Cleardata()
	{
	  if (_dataList != null)
	   {
		   _dataList.Clear();
	   }
	   if (_dataMap != null)
	   {
		   _dataMap.Clear();
	   }
	}
}

}

