
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class languagePack : Luban.BeanBase
{
    public languagePack(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        CN = _buf.ReadString();
        EN = _buf.ReadString();
        JP = _buf.ReadString();
//bindLanguageKeyFunc_impl
    }
	
//bindLanguageKeyField_impl

    public static languagePack DeserializelanguagePack(ByteBuf _buf)
    {
        return new languagePack(_buf);
    }

    /// <summary>
    /// key值
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string CN;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string EN;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string JP;
   
    public const int __ID__ = -2091975279;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "CN:" + CN + ","
        + "EN:" + EN + ","
        + "JP:" + JP + ","
        + "}";
    }
}

}

