
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public interface IVOFun
{
	void _LoadData(ByteBuf _buf);
	
	void _Cleardata();
}
public partial class Tables
{
    public Tblanguage Tblanguage {get; }
    public TblanguagePack TblanguagePack {get; }
    public Building.TbBuildingConfig TbBuildingConfig {get; }
    public Building.TbBuildingUpgradeConfig TbBuildingUpgradeConfig {get; }
    public Condition.TbConditionConfig TbConditionConfig {get; }
    public Guide.TbGuideConfig TbGuideConfig {get; }
    public Guide.TbGuideResConfig TbGuideResConfig {get; }

    public Tables()
    {
    }
    
    private void ResolveRef()
    {
    }
}

}
