
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TblanguagePack:IVOFun
{
	
    private readonly System.Collections.Generic.Dictionary<string, languagePack> _dataMap;
    private readonly System.Collections.Generic.List<languagePack> _dataList;
    
    public TblanguagePack()
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, languagePack>();
        _dataList = new System.Collections.Generic.List<languagePack>();
        
    }

    public System.Collections.Generic.Dictionary<string, languagePack> DataMap => _dataMap;
    public System.Collections.Generic.List<languagePack> DataList => _dataList;

    public languagePack GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public languagePack Get(string key) => _dataMap[key];
    public languagePack this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

	
	public void _LoadData(ByteBuf _buf)
	{
		 for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            languagePack _v;
	        _v = languagePack.DeserializelanguagePack(_buf);
			_dataList.Add(_v);
			_dataMap.Add(_v.Key, _v);
        }
	}
	
	public void _Cleardata()
	{
	  if (_dataList != null)
	   {
		   _dataList.Clear();
	   }
	   if (_dataMap != null)
	   {
		   _dataMap.Clear();
	   }
	}
}

}

