
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Building
{
public sealed partial class BuildingUpgradeConfig : Luban.BeanBase
{
    public BuildingUpgradeConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BuildingId = _buf.ReadInt();
        Level = _buf.ReadInt();
        UpgradeTime = _buf.ReadInt();
        UpgradeCostGold = _buf.ReadInt();
        UpgradeCostWood = _buf.ReadInt();
        UpgradeCostStone = _buf.ReadInt();
        ProduceMultiplier = _buf.ReadFloat();
        UnlockCondition = _buf.ReadString();
//bindLanguageKeyFunc_impl
    }
	
//bindLanguageKeyField_impl

    public static BuildingUpgradeConfig DeserializeBuildingUpgradeConfig(ByteBuf _buf)
    {
        return new Building.BuildingUpgradeConfig(_buf);
    }

    /// <summary>
    /// 升级配置ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 建筑ID（关联Building表）
    /// </summary>
    public readonly int BuildingId;
    /// <summary>
    /// 升级到的等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 升级时间（秒）
    /// </summary>
    public readonly int UpgradeTime;
    /// <summary>
    /// 升级消耗金币
    /// </summary>
    public readonly int UpgradeCostGold;
    /// <summary>
    /// 升级消耗木材
    /// </summary>
    public readonly int UpgradeCostWood;
    /// <summary>
    /// 升级消耗石头
    /// </summary>
    public readonly int UpgradeCostStone;
    /// <summary>
    /// 产出倍率加成
    /// </summary>
    public readonly float ProduceMultiplier;
    /// <summary>
    /// 升级条件
    /// </summary>
    public readonly string UnlockCondition;
   
    public const int __ID__ = -2094539152;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BuildingId:" + BuildingId + ","
        + "Level:" + Level + ","
        + "UpgradeTime:" + UpgradeTime + ","
        + "UpgradeCostGold:" + UpgradeCostGold + ","
        + "UpgradeCostWood:" + UpgradeCostWood + ","
        + "UpgradeCostStone:" + UpgradeCostStone + ","
        + "ProduceMultiplier:" + ProduceMultiplier + ","
        + "UnlockCondition:" + UnlockCondition + ","
        + "}";
    }
}

}

