
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Building
{
public sealed partial class BuildingConfig : Luban.BeanBase
{
    public BuildingConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        BuildingType = _buf.ReadInt();
        NameKey = _buf.ReadString();
        DescKey = _buf.ReadString();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Size = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); Size.Add(_e0);}}
        Icon = _buf.ReadString();
        PrefabPath = _buf.ReadString();
        UnlockCondition = _buf.ReadString();
        SortOrder = _buf.ReadInt();
//bindLanguageKeyFunc_impl
    }
	
//bindLanguageKeyField_impl

    public static BuildingConfig DeserializeBuildingConfig(ByteBuf _buf)
    {
        return new Building.BuildingConfig(_buf);
    }

    /// <summary>
    /// 建筑唯一ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 建筑类型（资源/防御/功能）
    /// </summary>
    public readonly int BuildingType;
    /// <summary>
    /// 建筑名称多语言Key
    /// </summary>
    public readonly string NameKey;
    /// <summary>
    /// 建筑描述多语言Key
    /// </summary>
    public readonly string DescKey;
    /// <summary>
    /// 建组大小占用网格
    /// </summary>
    public readonly System.Collections.Generic.List<int> Size;
    /// <summary>
    /// 建筑图标路径
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 建筑预制体路径
    /// </summary>
    public readonly string PrefabPath;
    /// <summary>
    /// 解锁条件
    /// </summary>
    public readonly string UnlockCondition;
    /// <summary>
    /// UI排序
    /// </summary>
    public readonly int SortOrder;
   
    public const int __ID__ = -610593392;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "BuildingType:" + BuildingType + ","
        + "NameKey:" + NameKey + ","
        + "DescKey:" + DescKey + ","
        + "Size:" + Luban.StringUtil.CollectionToString(Size) + ","
        + "Icon:" + Icon + ","
        + "PrefabPath:" + PrefabPath + ","
        + "UnlockCondition:" + UnlockCondition + ","
        + "SortOrder:" + SortOrder + ","
        + "}";
    }
}

}

