
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Building
{
public partial class TbBuildingConfig:IVOFun
{
	
    private readonly System.Collections.Generic.Dictionary<int, Building.BuildingConfig> _dataMap;
    private readonly System.Collections.Generic.List<Building.BuildingConfig> _dataList;
    
    public TbBuildingConfig()
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Building.BuildingConfig>();
        _dataList = new System.Collections.Generic.List<Building.BuildingConfig>();
        
    }

    public System.Collections.Generic.Dictionary<int, Building.BuildingConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Building.BuildingConfig> DataList => _dataList;

    public Building.BuildingConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Building.BuildingConfig Get(int key) => _dataMap[key];
    public Building.BuildingConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

	
	public void _LoadData(ByteBuf _buf)
	{
		 for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Building.BuildingConfig _v;
	        _v = Building.BuildingConfig.DeserializeBuildingConfig(_buf);
			_dataList.Add(_v);
			_dataMap.Add(_v.Id, _v);
        }
	}
	
	public void _Cleardata()
	{
	  if (_dataList != null)
	   {
		   _dataList.Clear();
	   }
	   if (_dataMap != null)
	   {
		   _dataMap.Clear();
	   }
	}
}

}

