
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Condition
{
public sealed partial class ConditionConfig : Luban.BeanBase
{
    public ConditionConfig(ByteBuf _buf) 
    {
        Key = _buf.ReadString();
        ConditionDesc = _buf.ReadString();
        ConditionFailDesc = _buf.ReadString();
        ConditionScripts = _buf.ReadString();
        ActionName = _buf.ReadString();
//bindLanguageKeyFunc_impl
    }
	
//bindLanguageKeyField_impl

    public static ConditionConfig DeserializeConditionConfig(ByteBuf _buf)
    {
        return new Condition.ConditionConfig(_buf);
    }

    /// <summary>
    /// key
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 文本描述（语言表ID）
    /// </summary>
    public readonly string ConditionDesc;
    /// <summary>
    /// 条件失败提示语
    /// </summary>
    public readonly string ConditionFailDesc;
    /// <summary>
    /// 条件检测脚本（必填）一个key对应一个脚本
    /// </summary>
    public readonly string ConditionScripts;
    /// <summary>
    /// 条件完成执行脚本
    /// </summary>
    public readonly string ActionName;
   
    public const int __ID__ = -186046166;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Key:" + Key + ","
        + "ConditionDesc:" + ConditionDesc + ","
        + "ConditionFailDesc:" + ConditionFailDesc + ","
        + "ConditionScripts:" + ConditionScripts + ","
        + "ActionName:" + ActionName + ","
        + "}";
    }
}

}

