
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Condition
{
public partial class TbConditionConfig:IVOFun
{
	
    private readonly System.Collections.Generic.Dictionary<string, Condition.ConditionConfig> _dataMap;
    private readonly System.Collections.Generic.List<Condition.ConditionConfig> _dataList;
    
    public TbConditionConfig()
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, Condition.ConditionConfig>();
        _dataList = new System.Collections.Generic.List<Condition.ConditionConfig>();
        
    }

    public System.Collections.Generic.Dictionary<string, Condition.ConditionConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<Condition.ConditionConfig> DataList => _dataList;

    public Condition.ConditionConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Condition.ConditionConfig Get(string key) => _dataMap[key];
    public Condition.ConditionConfig this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

	
	public void _LoadData(ByteBuf _buf)
	{
		 for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Condition.ConditionConfig _v;
	        _v = Condition.ConditionConfig.DeserializeConditionConfig(_buf);
			_dataList.Add(_v);
			_dataMap.Add(_v.Key, _v);
        }
	}
	
	public void _Cleardata()
	{
	  if (_dataList != null)
	   {
		   _dataList.Clear();
	   }
	   if (_dataMap != null)
	   {
		   _dataMap.Clear();
	   }
	}
}

}

